/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.uned.TFGDavidGiner.components.leafs;

import es.uned.TFGDavidGiner.core.LeafComponent;
import java.awt.Color;
import java.util.Set;

/**
 * Componente de hoja que encapsula un {@link javax.swing.JSlider} para gestionar
 * un valor de tipo {@link Integer} de forma segura.
 * <p>
 * Este componente extiende {@link LeafComponent} con el tipo genérico {@code Integer},
 * lo que garantiza la seguridad de tipos para el dato gestionado. Permite al usuario
 * seleccionar un valor numérico y lo valida para que esté en el rango de 0 a 100,
 * proporcionando retroalimentación visual en caso de error.
 *
 * @author david
 * @version 1.0
 * @since 12-07-2025
 */
public class ComponenteBInt extends LeafComponent {

    //<editor-fold defaultstate="collapsed" desc="Declaración de campos y constantes">
    /**
     * Color de fondo por defecto del componente cuando su estado es válido.
     */
    private static final java.awt.Color COLORINICIO = new java.awt.Color(242, 242, 242);

    /**
     * Almacena el valor numérico actual del componente. Es de tipo {@link Integer}.
     */
    private Integer data;

    /**
     * Define el nombre lógico de la propiedad principal que este componente representa.
     */
    private String propertyName = "Dato";

    /**
     * Almacena el mensaje de la última validación fallida.
     */
    private String error = "";

    /**
     * Define el conjunto de propiedades que pueden ser compartidas o enlazadas
     * con otros componentes del framework.
     */
    private static final Set<String> sharedProperties = Set.of("data", "propertyName");
    
    /**
     * Campo para la propiedad 'background', expuesto para mecanismos de data binding.
     * Almacena el color de fondo actual del componente.
     */
    Color background;
    //</editor-fold>

    /**
     * Constructor por defecto.
     * <p>
     * Inicializa los componentes visuales y establece el valor inicial de la
     * propiedad 'data' basándose en el valor por defecto del JSlider.
     */
    public ComponenteBInt() {
        initComponents();
        // Sincroniza el dato interno con el valor inicial del JSlider.
        this.data = this.jSlider1.getValue();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();

        jSlider1.setValue(0);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jSlider1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jSlider1PropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Manejador de eventos para cuando el valor del JSlider cambia.
    * <p>
    * Sincroniza el valor del slider con la propiedad 'data' del componente.
    *
    * @param evt El evento de cambio de estado.
    */
    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        setData(jSlider1.getValue());     
    }//GEN-LAST:event_jSlider1StateChanged

    /**
    * Manejador de eventos para cuando una propiedad del JSlider cambia.
    * <p>
    *
    * @param evt El evento de cambio de estado.
    */
    private void jSlider1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jSlider1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jSlider1PropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables

    //<editor-fold defaultstate="collapsed" desc="Getters y Setters de Propiedades">
    /**
     * Obtiene el valor de la propiedad principal ('data') del componente.
     * @return El valor actual como un {@code Integer}.
     */
    public Integer getData() {
        return data;
    }

    /**
     * Establece el valor de la propiedad principal ('data') del componente.
     * <p>
     * Actualiza el estado interno, sincroniza la vista (JSlider) y notifica
     * a los listeners de que la propiedad 'data' ha cambiado.
     *
     * @param dato El nuevo valor de tipo {@code Integer} para el componente.
     */
    public void setData(Integer dato) {
        Integer oldValue = this.data;
        if (oldValue == null || !oldValue.equals(dato)) {
            this.data = dato;
            // Actualiza la UI para que refleje el nuevo valor.
            jSlider1.setValue(dato);
            // Notifica a los listeners del cambio en la propiedad "data".
            firePropertyChange("data", oldValue, dato);
        }
    }

    /**
     * Obtiene el nombre lógico utilizado para identificar la propiedad principal
     * de este componente en el mecanismo de data-binding.
     *
     * @return El nombre de la propiedad, por ejemplo, "Dato".
     */
    public String getPropertyName() {
        return propertyName;
    }

    /**
     * Establece el nombre lógico para la propiedad principal de este componente.
     * <p>
     * Este nombre es crucial para que el sistema de data-binding pueda
     * sincronizar este componente con otros que gestionen una propiedad con el
     * mismo nombre.
     *
     * @param nombrePropiedad El nuevo nombre para la propiedad principal.
     */
    public void setPropertyName(String nombrePropiedad) {
        this.propertyName = nombrePropiedad;
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Implementación de la Interfaz Validation">
    /**
     * {@inheritDoc}
     * Restablece el componente a su estado inicial por defecto.
     *
     * @return {@code true} si la configuración fue exitosa, {@code false} en caso contrario.
     */
    @Override
    public boolean configurar() {
        try {
            setData(0);
            setBackground(COLORINICIO);
            error = "";
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    /**
     * {@inheritDoc}
     * Valida si el valor de 'data' se encuentra en el rango de 0 a 100.
     *
     * @return {@code true} si el valor es válido, {@code false} en caso contrario.
     */
    @Override
    public boolean validar() {
        if (data > 100 || data < 0) {
            this.setBackground(Color.red);
            error = this.getClass().getSimpleName() + ": El valor debe estar entre 0 y 100.";
            return false;
        } else {
            setBackground(COLORINICIO);
            error = "";
            return true;
        }
    }

    /**
     * {@inheritDoc}
     * @return El último mensaje de error de validación, o una cadena vacía si no hay error.
     */
    @Override
    public String getError() {
        return error;
    }
    //</editor-fold>

    /**
     * {@inheritDoc}
     * @return Un {@link Set} con los nombres de las propiedades compartidas.
     */
    @Override
    public Set<String> getSharedProperies() {
        return sharedProperties;
    }

}

