/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.uned.TFGDavidGiner.components.leafs;

import es.uned.TFGDavidGiner.core.LeafComponent;
import java.awt.Color;
import java.util.Set;

/**
 * Componente de hoja que encapsula un {@link javax.swing.JSpinner} para la
 * entrada de un valor numérico, gestionado como un {@link String}.
 * <p>
 * Este componente extiende {@link LeafComponent} y está diseñado para ser
 * una unidad básica de entrada de datos dentro de un framework más grande.
 * Implementa la interfaz {@link es.uned.TFGDavidGiner.core.interfaces.IValidation} para asegurar que el valor
 * introducido se encuentre dentro de un rango predefinido (0-100) y define
 * un conjunto de propiedades compartidas para la interacción con otros componentes.
 *
 * @author david
 * @version 1.0
 * @since 12-07-2025
 */
public class ComponenteAProperties extends LeafComponent {

    //<editor-fold defaultstate="collapsed" desc="Declaración de campos y constantes">
    /**
     * Color de fondo por defecto del componente cuando su estado es válido.
     */
    static final java.awt.Color COLORINICIO = new java.awt.Color(242, 242, 242);

    /**
     * Almacena el valor principal del componente como una cadena de texto.
     */
    private String data = "0";

    /**
     * Define el nombre lógico de la propiedad principal que este componente representa.
     */
    private String propertyName = "Dato";

    /**
     * Almacena el mensaje de la última validación fallida.
     */
    private String error = "";

    /**
     * Define el conjunto de propiedades que pueden ser compartidas o enlazadas
     * con otros componentes del framework (ej: 'data', 'background').
     */
    private static final Set<String> sharedProperties = Set.of("data", "propertyName", "background");

    /**
     * Campo para la propiedad 'background', expuesto para mecanismos de data binding.
     */
    private Color background;
    //</editor-fold>

    /**
     * Constructor por defecto.
     * <p>
     * Inicializa los componentes visuales de la interfaz de usuario.
     */
    public ComponenteAProperties() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(204, 204, 255));

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        jSpinner1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jSpinner1PropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSpinner1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Manejador de eventos para cuando el valor de una propiedad del JSpinner cambia.
     * <p>
     *
     * @param evt El evento de cambio de estado.
     */
    private void jSpinner1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jSpinner1PropertyChange
        // TODO add your handling code here:
                
    }//GEN-LAST:event_jSpinner1PropertyChange

    /**
     * Manejador de eventos para cuando el valor del JSpinner cambia.
     * <p>
     * Sincroniza el valor del spinner con la propiedad 'data' del componente.
     *
     * @param evt El evento de cambio de estado.
     */
    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        setData(jSpinner1.getValue().toString());
    }//GEN-LAST:event_jSpinner1StateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables

    /**
     * Obtiene el valor de la propiedad principal ('data') del componente.
     * @return El valor actual como un {@code Integer}.
     */
    public String getData() {
        return data;
    }

    /**
     * Establece el valor de la propiedad principal ('data') del componente.
     * <p>
     * Actualiza el estado interno, sincroniza la vista (JSpinner) y notifica
     * a los listeners de que la propiedad 'data' ha cambiado mediante un
     * {@code PropertyChangeEvent}.
     *
     * @param dato El nuevo valor de tipo {@code Integer} para el componente.
     */
    public void setData(String dato) {
        String oldValue = this.data;
        // Se comprueba si el valor realmente ha cambiado para evitar bucles de actualización.
        if (oldValue == null || !oldValue.equals(dato)) {
            this.data = dato;
            try {
                // Actualiza la UI para que refleje el nuevo valor.
                jSpinner1.setValue(Integer.parseInt(dato));
                // Notifica a los listeners del cambio en la propiedad "data".
                firePropertyChange("data", oldValue, dato);
            } catch (NumberFormatException e) {
                System.err.println("Error: El valor para 'data' no es un entero válido: " + dato);
            }
        }
    }

    /**
     * Obtiene el nombre lógico utilizado para identificar la propiedad principal
     * de este componente en el mecanismo de data-binding.
     *
     * @return El nombre de la propiedad, por ejemplo, "Dato".
     */
    public String getPropertyName() {
        return propertyName;
    }

    /**
     * Establece el nombre lógico para la propiedad principal de este componente.
     * <p>
     * Este nombre es crucial para que el sistema de data-binding pueda
     * sincronizar este componente con otros que gestionen una propiedad con el
     * mismo nombre.
     *
     * @param nombrePropiedad El nuevo nombre para la propiedad principal.
     */
    public void setPropertyName(String nombrePropiedad) {
        this.propertyName = nombrePropiedad;
    }

    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Implementación de la Interfaz Validation">
    /**
     * {@inheritDoc}
     * Restablece el componente a su estado inicial por defecto.
     *
     * @return {@code true} si la configuración fue exitosa, {@code false} en caso contrario.
     */
    @Override
    public boolean configurar() {
        try {
            setData("0");
            setBackground(COLORINICIO);
            error = "";
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    /**
     * {@inheritDoc}
     * Valida el estado actual del componente.
     * <p>
     * Comprueba si el valor de 'data' es un número entero en el rango de 0 a 100.
     * Si no es válido, cambia el color de fondo a rojo y establece un mensaje de error.
     *
     * @return {@code true} si el valor es válido, {@code false} en caso contrario.
     */
    @Override
    public boolean validar() {
        try {
            int valor = Integer.parseInt(data);
            if (valor > 100 || valor < 0) {
                this.setBackground(Color.red);
                error = this.getClass().getSimpleName() + ": El valor debe estar entre 0 y 100.";
                return false;
            } else {
                setBackground(COLORINICIO);
                error = "";
                return true;
            }
        } catch (NumberFormatException e) {
            this.setBackground(Color.red);
            error = this.getClass().getSimpleName() + ": El valor debe ser un número entero.";
            return false;
        }
    }

    /**
     * {@inheritDoc}
     * @return El último mensaje de error de validación, o una cadena vacía si no hay error.
     */
    @Override
    public String getError() {
        return error;
    }
    //</editor-fold>

    /**
     * {@inheritDoc}
     * @return Un {@link Set} con los nombres de las propiedades compartidas.
     */
    @Override
    public Set<String> getSharedProperies() {
        return sharedProperties;
    }
}

