/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.uned.TFGDavidGiner.components.leafs;

import es.uned.TFGDavidGiner.core.LeafComponent;
import java.awt.Color;
import java.util.Set;

/**
 * Componente de hoja que encapsula un {@link javax.swing.JSpinner} para gestionar un valor de tipo {@link Integer}.
 * <p>
 * Esta clase extiende {@link LeafComponent} con un tipo de dato genérico {@code Integer},
 * lo que simplifica la gestión y validación de datos numéricos. Implementa la interfaz
 * {@link es.uned.TFGDavidGiner.core.interfaces.IValidation} para asegurar que el valor se mantenga dentro de un rango predefinido (0-100).
 *
 * @author david
 * @version 1.0
 * @since 12-07-2025
 */
public class SpinnerPress extends LeafComponent {

    //<editor-fold defaultstate="collapsed" desc="Declaración de campos y constantes">
    /**
     * Almacena el color de fondo por defecto del componente para poder restaurarlo.
     */
    private final Color defaultBackgroundColor= this.getBackground();
    
    /**
     * Define el color que se usará para resaltar un error de validación.
     */
    private static final Color ERROR_COLOR = new Color(255, 51, 51); 

    /**
     * Almacena el valor numérico actual del componente.
     */
    private int pesoMaxPressBanca = 0;

    /**
     * Almacena el mensaje de la última validación fallida.
     */
    private String error = "";

    /**
     * Almacena el máximo valor admitido.
     */
    private int maxValor = 200;

    /**
     * Almacena el mínimo valor admitido.
     */
    private int minValor = 0;
    
    /**
     * Define el conjunto de propiedades que pueden ser compartidas o enlazadas
     * con otros componentes dentro del framework.
     */
    private static final Set<String> sharedProperties = Set.of("pesoMaxPressBanca");
    //</editor-fold>

    /**
     * Constructor por defecto.
     * <p>
     * Inicializa los componentes visuales de la interfaz de usuario.
     */
    public SpinnerPress() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 34));

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        jLabel1.setText("Press (Kg):");
        jLabel1.setMaximumSize(new java.awt.Dimension(75, 16));
        jLabel1.setMinimumSize(new java.awt.Dimension(75, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(75, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Manejador de eventos para cuando el valor del JSpinner cambia.
     * <p>
     * Sincroniza el valor del spinner con la propiedad 'data' del componente.
     *
     * @param evt El evento de cambio de estado.
     */
    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged

        // Actualiza el dato interno del componente con el nuevo valor del spinner.
        setPesoMaxPressBanca((Integer) jSpinner1.getValue());

    }//GEN-LAST:event_jSpinner1StateChanged

    //<editor-fold defaultstate="collapsed" desc="Getters y Setters de Propiedades">
    /**
     * Obtiene el valor de la propiedad principal ('data') del componente.
     * @return El valor actual como un {@code Integer}.
     */
    public int getPesoMaxPressBanca() {
       // System.out.println("Spinner getPesoMaxPressBanca: " + pesoMaxPressBanca.toString());
        return pesoMaxPressBanca;
    }

    /**
     * Establece el valor de la propiedad principal ('data') del componente.
     * <p>
     * Actualiza el estado interno, sincroniza la vista (JSpinner) y notifica
     * a los listeners de que la propiedad 'data' ha cambiado mediante un
     * {@code PropertyChangeEvent}.
     *
     * @param dato El nuevo valor de tipo {@code Integer} para el componente.
     */
    public void setPesoMaxPressBanca(int dato) {
        int oldValue = this.pesoMaxPressBanca;
        // Se comprueba si el valor realmente ha cambiado para evitar bucles de actualización.
        if (oldValue!=dato) {
            //System.out.println("Spinner setPesoMaxPressBanca: " + dato.toString());
            this.pesoMaxPressBanca = dato;
            // Actualiza la UI para que refleje el nuevo valor.
            jSpinner1.setValue(dato);
            // Notifica a los listeners del cambio en la propiedad "data".
            firePropertyChange("pesoMaxPressBanca", oldValue, dato);
        }
    }

    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Implementación de la Interfaz Validation">
    /**
     * {@inheritDoc}
     * Restablece el componente a su estado inicial por defecto.
     *
     * @return {@code true} si la configuración fue exitosa, {@code false} en caso contrario.
     */
    @Override
    public boolean configurar() {
        try {
            setPesoMaxPressBanca(0);
            setBackground(defaultBackgroundColor);
            error = "";
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    /**
     * {@inheritDoc}
     * <p>
     * Valida que el valor de la propiedad {@code pesoMaxPressBanca} se encuentre
     * dentro del rango definido por los campos {@code minValor} y {@code maxValor} (0-200).
     * Si el valor está fuera de rango, cambia el color de fondo del componente
     * a un color de error y prepara un mensaje descriptivo.
     *
     * @return {@code true} si el valor es válido, {@code false} en caso contrario.
     */
    @Override
    public boolean validar() {
        if (pesoMaxPressBanca > maxValor || pesoMaxPressBanca < minValor) {
            this.setBackground(ERROR_COLOR);
            error = "Press de banca: El valor debe estar entre " + minValor + " y " + maxValor + ".";
            return false;
        } else {
            setBackground(defaultBackgroundColor);
            error = "";
        }
        return true;
    }

    /**
     * {@inheritDoc}
     * @return El último mensaje de error de validación, o una cadena vacía si no hay error.
     */
    @Override
    public String getError() {
        return error;
    }
    //</editor-fold>

    /**
     * {@inheritDoc}
     * @return Un {@link Set} con los nombres de las propiedades compartidas.
     */
    @Override
    public Set<String> getSharedProperies() {
        return sharedProperties;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables

}

