/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.uned.TFGDavidGiner.demo;

import java.awt.Color;

/**
 * Ventana de demostración (JFrame) que muestra una disposición compleja de los
 * componentes personalizados del framework.
 * <p>
 * Esta clase sirve como un escaparate para probar y visualizar cómo interactúan
 * los diferentes tipos de contenedores ({@code SimpleContainer}, {@code TabContainer},
 * {@code TreeContainer}) y componentes de hoja ({@code ComponenteA}, {@code ComponenteB}, etc.),
 * tanto en sus versiones de tipo {@code String} como {@code Integer}.
 * La interfaz es generada en gran parte por un diseñador visual.
 *
 * @author david
 * @version 1.0
 * @since 2025-07-13
 */
public class DemoFrame2 extends javax.swing.JFrame {

    /**
     * Constructor por defecto.
     * <p>
     * Crea una nueva instancia de la ventana de demostración e inicializa
     * todos sus componentes visuales.
     */
    public DemoFrame2() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        treeContainer21 = new es.uned.TFGDavidGiner.components.containers.TreeContainer();
        simpleContainer1 = new es.uned.TFGDavidGiner.components.containers.SimpleContainer();
        componenteA1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteA();
        componenteB1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteB();
        simpleContainer2 = new es.uned.TFGDavidGiner.components.containers.SimpleContainer();
        treeContainer22 = new es.uned.TFGDavidGiner.components.containers.TreeContainer();
        componenteC1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteC();
        componenteD1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteD();
        tabContainer1 = new es.uned.TFGDavidGiner.components.containers.TabContainer();
        componenteA2 = new es.uned.TFGDavidGiner.components.leafs.ComponenteA();
        componenteB2 = new es.uned.TFGDavidGiner.components.leafs.ComponenteB();
        tabContainer2 = new es.uned.TFGDavidGiner.components.containers.TabContainer();
        componenteA3 = new es.uned.TFGDavidGiner.components.leafs.ComponenteA();
        componenteB3 = new es.uned.TFGDavidGiner.components.leafs.ComponenteB();
        componenteC2 = new es.uned.TFGDavidGiner.components.leafs.ComponenteC();
        componenteD2 = new es.uned.TFGDavidGiner.components.leafs.ComponenteD();
        tabContainer3 = new es.uned.TFGDavidGiner.components.containers.TabContainer();
        simpleContainer3 = new es.uned.TFGDavidGiner.components.containers.SimpleContainer();
        componenteBInt1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteBInt();
        componenteAInt1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteAInt();
        tabContainer4 = new es.uned.TFGDavidGiner.components.containers.TabContainer();
        componenteAInt2 = new es.uned.TFGDavidGiner.components.leafs.ComponenteAInt();
        componenteBInt2 = new es.uned.TFGDavidGiner.components.leafs.ComponenteBInt();
        componenteCInt1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteCInt();
        treeContainer23 = new es.uned.TFGDavidGiner.components.containers.TreeContainer();
        componenteAInt3 = new es.uned.TFGDavidGiner.components.leafs.ComponenteAInt();
        componenteBInt3 = new es.uned.TFGDavidGiner.components.leafs.ComponenteBInt();
        componenteCInt2 = new es.uned.TFGDavidGiner.components.leafs.ComponenteCInt();
        treeContainer24 = new es.uned.TFGDavidGiner.components.containers.TreeContainer();
        componenteA4 = new es.uned.TFGDavidGiner.components.leafs.ComponenteA();
        componenteB4 = new es.uned.TFGDavidGiner.components.leafs.ComponenteB();
        componenteC3 = new es.uned.TFGDavidGiner.components.leafs.ComponenteC();
        componenteD3 = new es.uned.TFGDavidGiner.components.leafs.ComponenteD();
        treeContainer25 = new es.uned.TFGDavidGiner.components.containers.TreeContainer();
        simpleContainer4 = new es.uned.TFGDavidGiner.components.containers.SimpleContainer();
        componenteA5 = new es.uned.TFGDavidGiner.components.leafs.ComponenteA();
        componenteB5 = new es.uned.TFGDavidGiner.components.leafs.ComponenteB();
        tabContainer5 = new es.uned.TFGDavidGiner.components.containers.TabContainer();
        componenteA6 = new es.uned.TFGDavidGiner.components.leafs.ComponenteA();
        componenteB6 = new es.uned.TFGDavidGiner.components.leafs.ComponenteB();
        componenteC4 = new es.uned.TFGDavidGiner.components.leafs.ComponenteC();
        componenteD4 = new es.uned.TFGDavidGiner.components.leafs.ComponenteD();
        treeContainer26 = new es.uned.TFGDavidGiner.components.containers.TreeContainer();
        componenteA7 = new es.uned.TFGDavidGiner.components.leafs.ComponenteA();
        componenteB7 = new es.uned.TFGDavidGiner.components.leafs.ComponenteB();
        componenteC5 = new es.uned.TFGDavidGiner.components.leafs.ComponenteC();
        componenteD5 = new es.uned.TFGDavidGiner.components.leafs.ComponenteD();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        treeContainer21.setDesignTimeSelectionPath("Raíz, TabContainers, Componentes");
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Raíz");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("SimpleContainers");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Básicos");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Componentes");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("TabContainers");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Básicos");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Componentes");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("TreeContainers");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Básicos");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Componentes");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeContainer21.setEstructuraArbol(new javax.swing.tree.DefaultTreeModel(treeNode1));

        simpleContainer1.setDividerLocation(200);
        simpleContainer1.setDividerSize(2);
        simpleContainer1.setOrientation(es.uned.TFGDavidGiner.core.SplitOrientation.VERTICAL);
        simpleContainer1.getContentPane().add(componenteA1);
        simpleContainer1.getContentPane().add(componenteB1);

        treeContainer21.getContentPane().add(simpleContainer1);
        simpleContainer1.setBounds(60, 250, 200, 150);

        simpleContainer2.setDividerLocation(200);
        simpleContainer2.setOrientation(es.uned.TFGDavidGiner.core.SplitOrientation.VERTICAL);

        treeContainer22.setDesignTimeSelectionPath("Raíz, C1");
        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Raíz");
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("C1");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("C2");
        treeNode1.add(treeNode2);
        treeContainer22.setEstructuraArbol(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treeContainer22.getContentPane().add(componenteC1);
        componenteC1.setBounds(0, 80, 189, 43);
        treeContainer22.getContentPane().add(componenteD1);
        componenteD1.setBounds(60, 110, 114, 38);

        simpleContainer2.getContentPane().add(treeContainer22);

        tabContainer1.getContentPane().add(componenteA2);
        tabContainer1.getContentPane().add(componenteB2);

        simpleContainer2.getContentPane().add(tabContainer1);

        treeContainer21.getContentPane().add(simpleContainer2);
        simpleContainer2.setBounds(20, 120, 200, 150);

        tabContainer2.getContentPane().add(componenteA3);
        tabContainer2.getContentPane().add(componenteB3);
        tabContainer2.getContentPane().add(componenteC2);
        tabContainer2.getContentPane().add(componenteD2);

        treeContainer21.getContentPane().add(tabContainer2);
        tabContainer2.setBounds(50, 160, 200, 150);

        tabContainer3.setTabTitles("SimpleContainer,TabContainer,TreeContainer");

        simpleContainer3.setDividerLocation(200);
        simpleContainer3.setDividerSize(2);
        simpleContainer3.getContentPane().add(componenteBInt1);
        simpleContainer3.getContentPane().add(componenteAInt1);

        tabContainer3.getContentPane().add(simpleContainer3);

        tabContainer4.setTabTitles("AInt, BInt, CInt");
        tabContainer4.getContentPane().add(componenteAInt2);
        tabContainer4.getContentPane().add(componenteBInt2);
        tabContainer4.getContentPane().add(componenteCInt1);

        tabContainer3.getContentPane().add(tabContainer4);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Componentes Int");
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("AInt");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("BInt");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("CInt");
        treeNode1.add(treeNode2);
        treeContainer23.setEstructuraArbol(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treeContainer23.getContentPane().add(componenteAInt3);
        componenteAInt3.setBounds(70, 140, 114, 38);
        treeContainer23.getContentPane().add(componenteBInt3);
        componenteBInt3.setBounds(20, 180, 212, 38);
        treeContainer23.getContentPane().add(componenteCInt2);
        componenteCInt2.setBounds(50, 220, 212, 38);

        tabContainer3.getContentPane().add(treeContainer23);

        treeContainer21.getContentPane().add(tabContainer3);
        tabContainer3.setBounds(10, 140, 200, 150);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Componentes");
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("C1");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("C2");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("C3");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("C4");
        treeNode1.add(treeNode2);
        treeContainer24.setEstructuraArbol(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treeContainer24.getContentPane().add(componenteA4);
        componenteA4.setBounds(40, 170, 114, 38);
        treeContainer24.getContentPane().add(componenteB4);
        componenteB4.setBounds(40, 240, 212, 38);
        treeContainer24.getContentPane().add(componenteC3);
        componenteC3.setBounds(140, 270, 189, 43);
        treeContainer24.getContentPane().add(componenteD3);
        componenteD3.setBounds(160, 300, 114, 38);

        treeContainer21.getContentPane().add(treeContainer24);
        treeContainer24.setBounds(20, 20, 400, 400);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Contenedores");
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("SimpleContainer");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("TabContainer");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("TreeContainer");
        treeNode1.add(treeNode2);
        treeContainer25.setEstructuraArbol(new javax.swing.tree.DefaultTreeModel(treeNode1));

        simpleContainer4.setOrientation(es.uned.TFGDavidGiner.core.SplitOrientation.VERTICAL);
        simpleContainer4.getContentPane().add(componenteA5);
        simpleContainer4.getContentPane().add(componenteB5);

        treeContainer25.getContentPane().add(simpleContainer4);
        simpleContainer4.setBounds(0, 170, 200, 150);

        tabContainer5.setTabTitles("ComponenteA,ComponenteB,ComponenteC,ComponenteD");
        tabContainer5.getContentPane().add(componenteA6);
        tabContainer5.getContentPane().add(componenteB6);
        tabContainer5.getContentPane().add(componenteC4);
        tabContainer5.getContentPane().add(componenteD4);

        treeContainer25.getContentPane().add(tabContainer5);
        tabContainer5.setBounds(50, 150, 200, 150);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Componentes");
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("ComponenteA");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("ComponenteB");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("ComponenteC");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("ComponenteD");
        treeNode1.add(treeNode2);
        treeContainer26.setEstructuraArbol(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treeContainer26.getContentPane().add(componenteA7);
        componenteA7.setBounds(50, 140, 114, 38);
        treeContainer26.getContentPane().add(componenteB7);
        componenteB7.setBounds(40, 200, 212, 38);
        treeContainer26.getContentPane().add(componenteC5);
        componenteC5.setBounds(70, 250, 189, 43);
        treeContainer26.getContentPane().add(componenteD5);
        componenteD5.setBounds(90, 320, 114, 38);

        treeContainer25.getContentPane().add(treeContainer26);
        treeContainer26.setBounds(10, 70, 400, 400);

        treeContainer21.getContentPane().add(treeContainer25);
        treeContainer25.setBounds(30, 80, 400, 400);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(treeContainer21, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(treeContainer21, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Manejador de eventos para el clic en {@code jButton1}.
    * <p>
    * Cambia el color de fondo de un componente específico ({@code componenteD5}) a rojo
    * para demostrar la interacción y el acceso a los componentes anidados.
    *
    * @param evt El evento de acción.
    */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        componenteD5.setBackground(Color.red);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * El punto de entrada principal de la aplicación.
     *
     * @param args los argumentos de la línea de comandos (no se utilizan).
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemoFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

         /* Crea y muestra el formulario en el Event Dispatch Thread de Swing */
        java.awt.EventQueue.invokeLater(() -> new DemoFrame2().setVisible(true));
    }

    //<editor-fold defaultstate="collapsed" desc="Declaración de variables de componentes de la UI">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private es.uned.TFGDavidGiner.components.leafs.ComponenteA componenteA1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteA componenteA2;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteA componenteA3;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteA componenteA4;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteA componenteA5;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteA componenteA6;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteA componenteA7;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteAInt componenteAInt1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteAInt componenteAInt2;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteAInt componenteAInt3;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteB componenteB1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteB componenteB2;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteB componenteB3;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteB componenteB4;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteB componenteB5;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteB componenteB6;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteB componenteB7;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteBInt componenteBInt1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteBInt componenteBInt2;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteBInt componenteBInt3;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteC componenteC1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteC componenteC2;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteC componenteC3;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteC componenteC4;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteC componenteC5;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteCInt componenteCInt1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteCInt componenteCInt2;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteD componenteD1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteD componenteD2;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteD componenteD3;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteD componenteD4;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteD componenteD5;
    private javax.swing.JButton jButton1;
    private es.uned.TFGDavidGiner.components.containers.SimpleContainer simpleContainer1;
    private es.uned.TFGDavidGiner.components.containers.SimpleContainer simpleContainer2;
    private es.uned.TFGDavidGiner.components.containers.SimpleContainer simpleContainer3;
    private es.uned.TFGDavidGiner.components.containers.SimpleContainer simpleContainer4;
    private es.uned.TFGDavidGiner.components.containers.TabContainer tabContainer1;
    private es.uned.TFGDavidGiner.components.containers.TabContainer tabContainer2;
    private es.uned.TFGDavidGiner.components.containers.TabContainer tabContainer3;
    private es.uned.TFGDavidGiner.components.containers.TabContainer tabContainer4;
    private es.uned.TFGDavidGiner.components.containers.TabContainer tabContainer5;
    private es.uned.TFGDavidGiner.components.containers.TreeContainer treeContainer21;
    private es.uned.TFGDavidGiner.components.containers.TreeContainer treeContainer22;
    private es.uned.TFGDavidGiner.components.containers.TreeContainer treeContainer23;
    private es.uned.TFGDavidGiner.components.containers.TreeContainer treeContainer24;
    private es.uned.TFGDavidGiner.components.containers.TreeContainer treeContainer25;
    private es.uned.TFGDavidGiner.components.containers.TreeContainer treeContainer26;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
