/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.uned.TFGDavidGiner.demo;

import java.awt.Color;

/**
 * Ventana de demostración (JFrame) para visualizar y probar varios componentes
 * personalizados con diferentes propiedades, organizados en contenedores anidados.
 * <p>
 * Esta clase sirve como un entorno de prueba para observar el comportamiento de
 * los componentes de hoja ({@code ComponenteA}, {@code ComponenteB}, etc.) cuando
 * se agrupan dentro de contenedores como {@code TabContainer} y {@code SimpleContainer}.
 *
 * @author david
 * @version 1.0
 * @since 2025-07-13
 */
public class FrameVariasPropiedades extends javax.swing.JFrame {

    /**
     * Constructor por defecto.
     * <p>
     * Crea una nueva instancia de la ventana de demostración e inicializa
     * todos sus componentes visuales.
     */
    public FrameVariasPropiedades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabContainer1 = new es.uned.TFGDavidGiner.components.containers.TabContainer();
        simpleContainer1 = new es.uned.TFGDavidGiner.components.containers.SimpleContainer();
        componenteB1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteB();
        componenteA1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteA();
        componenteC1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteC();
        componenteD1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteD();
        componenteAInt1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteAInt();
        componenteBInt1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteBInt();
        componenteCInt1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteCInt();
        componenteA3 = new es.uned.TFGDavidGiner.components.leafs.ComponenteA();
        jButton1 = new javax.swing.JButton();
        simpleContainer2 = new es.uned.TFGDavidGiner.components.containers.SimpleContainer();
        componenteA2 = new es.uned.TFGDavidGiner.components.leafs.ComponenteA();
        componenteB2 = new es.uned.TFGDavidGiner.components.leafs.ComponenteB();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabContainer1.setTabTitles("Pestaña 1,Pestaña 2,Pestaña 3,Pestaña 4,Pestaña 5");

        simpleContainer1.getContentPane().add(componenteB1);
        simpleContainer1.getContentPane().add(componenteA1);

        tabContainer1.getContentPane().add(simpleContainer1);
        tabContainer1.getContentPane().add(componenteC1);
        tabContainer1.getContentPane().add(componenteD1);
        tabContainer1.getContentPane().add(componenteAInt1);
        tabContainer1.getContentPane().add(componenteBInt1);
        tabContainer1.getContentPane().add(componenteCInt1);
        tabContainer1.getContentPane().add(componenteA3);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        simpleContainer2.getContentPane().add(componenteA2);
        simpleContainer2.getContentPane().add(componenteB2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(99, 99, 99)
                        .addComponent(simpleContainer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tabContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tabContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(simpleContainer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Manejador de eventos para el clic en {@code jButton1}.
    * <p>
    * Cambia el color de fondo de {@code componenteB1} a rojo para demostrar
    * la capacidad de interactuar programáticamente con los componentes.
    *
    * @param evt El evento de acción.
    */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.componenteB1.setBackground(Color.red);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * El punto de entrada principal de la aplicación.
     *
     * @param args los argumentos de la línea de comandos (no se utilizan).
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameVariasPropiedades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Crea y muestra el formulario en el Event Dispatch Thread de Swing */
        java.awt.EventQueue.invokeLater(() -> new FrameVariasPropiedades().setVisible(true));
    }

    //<editor-fold defaultstate="collapsed" desc="Declaración de variables de componentes de la UI">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private es.uned.TFGDavidGiner.components.leafs.ComponenteA componenteA1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteA componenteA2;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteA componenteA3;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteAInt componenteAInt1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteB componenteB1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteB componenteB2;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteBInt componenteBInt1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteC componenteC1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteCInt componenteCInt1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteD componenteD1;
    private javax.swing.JButton jButton1;
    private es.uned.TFGDavidGiner.components.containers.SimpleContainer simpleContainer1;
    private es.uned.TFGDavidGiner.components.containers.SimpleContainer simpleContainer2;
    private es.uned.TFGDavidGiner.components.containers.TabContainer tabContainer1;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
