/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.uned.TFGDavidGiner.demo;

import es.uned.TFGDavidGiner.components.modelo.Usuario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author david
 */
public class GimnasioDemoFrame2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GimnasioDemoFrame2.class.getName());

    /**
     * Creates new form gimnasionDemoFrame2
     */
    public GimnasioDemoFrame2() {
        initComponents();
         // Carga de Datos de Prueba ---
        tablaUsuarios1.setUsuarios(crearDatosDePrueba());
        
        // NOTA: No es necesario añadir listeners manualmente. El framework se encarga
        // del data binding automático porque los 3 componentes hoja comparten la
        // propiedad "usuarioSeleccionado" y están dentro del mismo BaseContainer.
        
        // Finalización ---
        this.pack();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); // Iniciar maximizado
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanelContainer1 = new es.uned.TFGDavidGiner.components.containers.ButtonPanelContainer();
        treeContainer1 = new es.uned.TFGDavidGiner.components.containers.TreeContainer();
        simpleContainer1 = new es.uned.TFGDavidGiner.components.containers.SimpleContainer();
        tablaUsuarios1 = new es.uned.TFGDavidGiner.components.leafs.TablaUsuarios();
        tabContainer1 = new es.uned.TFGDavidGiner.components.containers.TabContainer();
        panelDatosUsuario1 = new es.uned.TFGDavidGiner.components.leafs.PanelDatosUsuario();
        graficoRendimiento1 = new es.uned.TFGDavidGiner.components.leafs.GraficoRendimiento();
        simpleContainer2 = new es.uned.TFGDavidGiner.components.containers.SimpleContainer();
        simpleContainer3 = new es.uned.TFGDavidGiner.components.containers.SimpleContainer();
        spinnerSquad1 = new es.uned.TFGDavidGiner.components.leafs.SpinnerSquad();
        spinnerPress1 = new es.uned.TFGDavidGiner.components.leafs.SpinnerPress();
        graficoRendimiento2 = new es.uned.TFGDavidGiner.components.leafs.GraficoRendimiento();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        treeContainer1.setDesignTimeSelectionPath("Raíz");
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Raíz");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Datos Generales");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Capacidades Físicas");
        treeNode1.add(treeNode2);
        treeContainer1.setEstructuraArbol(new javax.swing.tree.DefaultTreeModel(treeNode1));

        simpleContainer1.setDividerLocation(180);
        simpleContainer1.setOrientation(es.uned.TFGDavidGiner.core.SplitOrientation.VERTICAL);
        simpleContainer1.getContentPane().add(tablaUsuarios1);

        tabContainer1.setTabTitles("Datos Usuario, Gráfico Rendimiento");
        tabContainer1.getContentPane().add(panelDatosUsuario1);
        tabContainer1.getContentPane().add(graficoRendimiento1);

        simpleContainer1.getContentPane().add(tabContainer1);

        treeContainer1.getContentPane().add(simpleContainer1);
        simpleContainer1.setBounds(210, 140, 200, 150);

        simpleContainer3.setOrientation(es.uned.TFGDavidGiner.core.SplitOrientation.VERTICAL);
        simpleContainer3.getContentPane().add(spinnerSquad1);
        simpleContainer3.getContentPane().add(spinnerPress1);

        simpleContainer2.getContentPane().add(simpleContainer3);
        simpleContainer2.getContentPane().add(graficoRendimiento2);

        treeContainer1.getContentPane().add(simpleContainer2);
        simpleContainer2.setBounds(-170, 120, 200, 150);

        buttonPanelContainer1.getContentPane().add(treeContainer1);

        getContentPane().add(buttonPanelContainer1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GimnasioDemoFrame2().setVisible(true));
    }

        /**
     * Crea una lista de usuarios de ejemplo para poblar la tabla.
     * @return Una lista de objetos Usuario.
     */
    private List<Usuario> crearDatosDePrueba() {
        List<Usuario> usuarios = new ArrayList<>();
        usuarios.add(new Usuario("Ana", "García", "Intermedio", 60, 90));
        usuarios.add(new Usuario("Carlos", "Martínez", "Avanzado", 120, 160));
        usuarios.add(new Usuario("Elena", "Ruiz", "Principiante", 30, 40));
        return usuarios;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private es.uned.TFGDavidGiner.components.containers.ButtonPanelContainer buttonPanelContainer1;
    private es.uned.TFGDavidGiner.components.leafs.GraficoRendimiento graficoRendimiento1;
    private es.uned.TFGDavidGiner.components.leafs.GraficoRendimiento graficoRendimiento2;
    private es.uned.TFGDavidGiner.components.leafs.PanelDatosUsuario panelDatosUsuario1;
    private es.uned.TFGDavidGiner.components.containers.SimpleContainer simpleContainer1;
    private es.uned.TFGDavidGiner.components.containers.SimpleContainer simpleContainer2;
    private es.uned.TFGDavidGiner.components.containers.SimpleContainer simpleContainer3;
    private es.uned.TFGDavidGiner.components.leafs.SpinnerPress spinnerPress1;
    private es.uned.TFGDavidGiner.components.leafs.SpinnerSquad spinnerSquad1;
    private es.uned.TFGDavidGiner.components.containers.TabContainer tabContainer1;
    private es.uned.TFGDavidGiner.components.leafs.TablaUsuarios tablaUsuarios1;
    private es.uned.TFGDavidGiner.components.containers.TreeContainer treeContainer1;
    // End of variables declaration//GEN-END:variables
}
