/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.uned.TFGDavidGiner.demo;

import java.awt.Color;

/**
 * Ventana de demostración (JFrame) simple para probar la interacción entre
 * un {@link es.uned.TFGDavidGiner.components.containers.SimpleContainer} y dos 
 * componentes de hoja ({@link es.uned.TFGDavidGiner.components.leafs.ComponenteA} 
 * y {@link es.uned.TFGDavidGiner.components.leafs.ComponenteB}).
 * <p>
 * Esta clase sirve como un entorno de prueba básico para visualizar cómo se
 * anidan los componentes y cómo se puede interactuar con ellos mediante un botón.
 *
 * @author david
 * @version 1.0
 * @since 2025-07-13
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Constructor por defecto.
     * <p>
     * Crea una nueva instancia de la ventana de demostración e inicializa
     * todos sus componentes visuales.
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        simpleContainer1 = new es.uned.TFGDavidGiner.components.containers.SimpleContainer();
        componenteB1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteB();
        componenteA1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteA();
        treeContainer1 = new es.uned.TFGDavidGiner.components.containers.TreeContainer();
        componenteA2 = new es.uned.TFGDavidGiner.components.leafs.ComponenteA();
        componenteB2 = new es.uned.TFGDavidGiner.components.leafs.ComponenteB();
        componenteC1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteC();
        simpleContainer2 = new es.uned.TFGDavidGiner.components.containers.SimpleContainer();
        componenteB3 = new es.uned.TFGDavidGiner.components.leafs.ComponenteB();
        componenteA3 = new es.uned.TFGDavidGiner.components.leafs.ComponenteA();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        simpleContainer1.getContentPane().add(componenteB1);
        simpleContainer1.getContentPane().add(componenteA1);

        treeContainer1.setDesignTimeSelectionPath("Raíz, C3, C4");
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Raíz");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("C1");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("C2");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("C3");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("C4");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeContainer1.setEstructuraArbol(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treeContainer1.getContentPane().add(componenteA2);
        componenteA2.setBounds(10, 80, 114, 38);
        treeContainer1.getContentPane().add(componenteB2);
        componenteB2.setBounds(90, 150, 212, 38);
        treeContainer1.getContentPane().add(componenteC1);
        componenteC1.setBounds(30, 140, 189, 43);

        simpleContainer2.setDividerLocation(150);
        simpleContainer2.getContentPane().add(componenteB3);
        simpleContainer2.getContentPane().add(componenteA3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(simpleContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(simpleContainer2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(treeContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(simpleContainer2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpleContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(treeContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Manejador de eventos para el clic en {@code jButton1}.
     * <p>
     * Cambia el color de fondo de {@code componenteB1} a rojo para demostrar
     * la capacidad de interactuar programáticamente con los componentes anidados.
     *
     * @param evt El evento de acción.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.componenteB1.setBackground(Color.red);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * El punto de entrada principal de la aplicación de demostración.
     *
     * @param args los argumentos de la línea de comandos (no se utilizan).
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Crea y muestra el formulario en el Event Dispatch Thread de Swing */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    //<editor-fold defaultstate="collapsed" desc="Declaración de variables de componentes de la UI">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private es.uned.TFGDavidGiner.components.leafs.ComponenteA componenteA1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteA componenteA2;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteA componenteA3;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteB componenteB1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteB componenteB2;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteB componenteB3;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteC componenteC1;
    private javax.swing.JButton jButton1;
    private es.uned.TFGDavidGiner.components.containers.SimpleContainer simpleContainer1;
    private es.uned.TFGDavidGiner.components.containers.SimpleContainer simpleContainer2;
    private es.uned.TFGDavidGiner.components.containers.TreeContainer treeContainer1;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
