/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.uned.TFGDavidGiner.demo;

/**
 * Ventana de demostración (JFrame) para visualizar un {@link es.uned.TFGDavidGiner.components.containers.TreeContainer}
 * con un único componente de hoja anidado.
 * <p>
 * Esta clase sirve como un entorno de prueba minimalista para verificar el
 * funcionamiento básico del {@code TreeContainer} y su capacidad para
 * mostrar un componente hijo, en este caso, un {@link es.uned.TFGDavidGiner.components.leafs.ComponenteA}.
 *
 * @author dginer
 * @version 1.0
 * @since 2025-07-13
 */
public class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Constructor por defecto.
     * <p>
     * Crea una nueva instancia de la ventana de demostración e inicializa
     * todos sus componentes visuales.
     */
    public NewJFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        treeContainer21 = new es.uned.TFGDavidGiner.components.containers.TreeContainer();
        componenteA1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteA();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        treeContainer21.setDesignTimeSelectionPath("JTree, colors, blue");
        treeContainer21.getContentPane().add(componenteA1);
        componenteA1.setBounds(90, 120, 114, 38);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(treeContainer21, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(treeContainer21, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * El punto de entrada principal de la aplicación de demostración.
     *
     * @param args los argumentos de la línea de comandos (no se utilizan).
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Crea y muestra el formulario en el Event Dispatch Thread de Swing */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame1().setVisible(true));
    }

    //<editor-fold defaultstate="collapsed" desc="Declaración de variables de componentes de la UI">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private es.uned.TFGDavidGiner.components.leafs.ComponenteA componenteA1;
    private es.uned.TFGDavidGiner.components.containers.TreeContainer treeContainer21;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
