/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.uned.TFGDavidGiner.demo;

/**
 *
 * @author david
 */
public class NewJFrame2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame2.class.getName());

    /**
     * Creates new form NewJFrame2
     */
    public NewJFrame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabContainer1 = new es.uned.TFGDavidGiner.components.containers.TabContainer();
        componenteC1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteC();
        componenteA1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteA();
        componenteC2 = new es.uned.TFGDavidGiner.components.leafs.ComponenteC();
        componenteA2 = new es.uned.TFGDavidGiner.components.leafs.ComponenteA();
        componenteB1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteB();
        componenteD1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteD();
        componenteAInt1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteAInt();
        componenteBInt1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteBInt();
        componenteCInt1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteCInt();
        componenteBInt2 = new es.uned.TFGDavidGiner.components.leafs.ComponenteBInt();
        componenteCInt2 = new es.uned.TFGDavidGiner.components.leafs.ComponenteCInt();
        componenteAInt2 = new es.uned.TFGDavidGiner.components.leafs.ComponenteAInt();
        treeContainer1 = new es.uned.TFGDavidGiner.components.containers.TreeContainer();
        tabContainer3 = new es.uned.TFGDavidGiner.components.containers.TabContainer();
        simpleContainer2 = new es.uned.TFGDavidGiner.components.containers.SimpleContainer();
        treeContainer2 = new es.uned.TFGDavidGiner.components.containers.TreeContainer();
        tabContainer2 = new es.uned.TFGDavidGiner.components.containers.TabContainer();
        simpleContainer1 = new es.uned.TFGDavidGiner.components.containers.SimpleContainer();
        treeContainer3 = new es.uned.TFGDavidGiner.components.containers.TreeContainer();
        treeContainer4 = new es.uned.TFGDavidGiner.components.containers.TreeContainer();
        componenteA3 = new es.uned.TFGDavidGiner.components.leafs.ComponenteA();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabContainer1.getContentPane().add(componenteC1);
        tabContainer1.getContentPane().add(componenteA1);
        tabContainer1.getContentPane().add(componenteC2);
        tabContainer1.getContentPane().add(componenteA2);
        tabContainer1.getContentPane().add(componenteB1);
        tabContainer1.getContentPane().add(componenteD1);
        tabContainer1.getContentPane().add(componenteAInt1);
        tabContainer1.getContentPane().add(componenteBInt1);
        tabContainer1.getContentPane().add(componenteCInt1);
        tabContainer1.getContentPane().add(componenteBInt2);
        tabContainer1.getContentPane().add(componenteCInt2);
        tabContainer1.getContentPane().add(componenteAInt2);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("JTree");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("colors");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("blue");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("violet");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("red");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeContainer1.setEstructuraArbol(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treeContainer1.getContentPane().add(tabContainer3);
        tabContainer3.setBounds(30, 30, 200, 150);
        treeContainer1.getContentPane().add(simpleContainer2);
        simpleContainer2.setBounds(20, 30, 200, 150);
        treeContainer1.getContentPane().add(treeContainer2);
        treeContainer2.setBounds(-230, -100, 400, 400);

        tabContainer1.getContentPane().add(treeContainer1);
        tabContainer1.getContentPane().add(tabContainer2);
        tabContainer1.getContentPane().add(simpleContainer1);
        tabContainer1.getContentPane().add(treeContainer3);

        treeContainer4.setDesignTimeSelectionPath("JTree, colors, blue");
        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("JTree");
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("colors");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("blue");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeContainer4.setEstructuraArbol(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treeContainer4.getContentPane().add(componenteA3);
        componenteA3.setBounds(-70, 0, 114, 34);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(treeContainer4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(340, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(tabContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(treeContainer4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private es.uned.TFGDavidGiner.components.leafs.ComponenteA componenteA1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteA componenteA2;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteA componenteA3;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteAInt componenteAInt1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteAInt componenteAInt2;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteB componenteB1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteBInt componenteBInt1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteBInt componenteBInt2;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteC componenteC1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteC componenteC2;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteCInt componenteCInt1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteCInt componenteCInt2;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteD componenteD1;
    private es.uned.TFGDavidGiner.components.containers.SimpleContainer simpleContainer1;
    private es.uned.TFGDavidGiner.components.containers.SimpleContainer simpleContainer2;
    private es.uned.TFGDavidGiner.components.containers.TabContainer tabContainer1;
    private es.uned.TFGDavidGiner.components.containers.TabContainer tabContainer2;
    private es.uned.TFGDavidGiner.components.containers.TabContainer tabContainer3;
    private es.uned.TFGDavidGiner.components.containers.TreeContainer treeContainer1;
    private es.uned.TFGDavidGiner.components.containers.TreeContainer treeContainer2;
    private es.uned.TFGDavidGiner.components.containers.TreeContainer treeContainer3;
    private es.uned.TFGDavidGiner.components.containers.TreeContainer treeContainer4;
    // End of variables declaration//GEN-END:variables
}
