/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.uned.TFGDavidGiner.demo;

/**
 * Ventana principal de demostración que prueba el anidamiento y la funcionalidad
 * de los componentes reutilizables de la biblioteca.
 * <p>
 * Esta clase, diseñada con el editor visual de NetBeans, sirve como un escaparate
 * para mostrar cómo los diferentes contenedores ({@code TreeContainer}, 
 * {@code TabContainer}, etc.) y componentes hoja ({@code ComponenteA}, 
 * {@code ComponenteB}, etc.) pueden ser ensamblados visualmente desde la paleta
 * de componentes para crear una interfaz de usuario compleja y jerárquica.
 * <p>
 * La estructura anidada y la botonera demuestran la aplicación de los patrones
 * de diseño Composite y Command para la validación atómica de la edición.
 *
 * @author dginer
 * @version 1.0
 * @since 2025-07-13
 */
public class PruebaComponentesPaleta extends javax.swing.JFrame {

    /**
     * Constructor por defecto.
     * Crea una nueva instancia del formulario de prueba e inicializa todos los
     * componentes gráficos llamando a {@link #initComponents()}.
     */
    public PruebaComponentesPaleta() {
        initComponents();
    }

    /**
     * Inicializa los componentes de la interfaz gráfica.
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanelContainer1 = new es.uned.TFGDavidGiner.components.containers.ButtonPanelContainer();
        treeContainer2 = new es.uned.TFGDavidGiner.components.containers.TreeContainer();
        componenteA1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteA();
        componenteB1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteB();
        componenteC1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteC();
        componenteD1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteD();
        componenteAInt1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteAInt();
        componenteBInt1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteBInt();
        componenteCInt1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteCInt();
        simpleContainer1 = new es.uned.TFGDavidGiner.components.containers.SimpleContainer();
        componenteB2 = new es.uned.TFGDavidGiner.components.leafs.ComponenteB();
        componenteA2 = new es.uned.TFGDavidGiner.components.leafs.ComponenteA();
        tabContainer1 = new es.uned.TFGDavidGiner.components.containers.TabContainer();
        componenteAInt2 = new es.uned.TFGDavidGiner.components.leafs.ComponenteAInt();
        componenteBInt2 = new es.uned.TFGDavidGiner.components.leafs.ComponenteBInt();
        componenteCInt2 = new es.uned.TFGDavidGiner.components.leafs.ComponenteCInt();
        treeContainer1 = new es.uned.TFGDavidGiner.components.containers.TreeContainer();
        componenteA3 = new es.uned.TFGDavidGiner.components.leafs.ComponenteA();
        componenteB3 = new es.uned.TFGDavidGiner.components.leafs.ComponenteB();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Raíz");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Grupo1");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ComponenteA");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ComponenteB");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ComponenteC");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ComponenteD");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ComponenteAInt");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ComponenteBInt");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ComponenteCInt");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Grupo2");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Simplecontainer");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("TabContainer");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Grupo3");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("TreeContainer");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeContainer2.setEstructuraArbol(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treeContainer2.getContentPane().add(componenteA1);
        componenteA1.setBounds(390, 90, 114, 38);
        treeContainer2.getContentPane().add(componenteB1);
        componenteB1.setBounds(350, 110, 212, 38);
        treeContainer2.getContentPane().add(componenteC1);
        componenteC1.setBounds(390, 140, 189, 43);
        treeContainer2.getContentPane().add(componenteD1);
        componenteD1.setBounds(340, 190, 114, 38);
        treeContainer2.getContentPane().add(componenteAInt1);
        componenteAInt1.setBounds(350, 120, 114, 38);
        treeContainer2.getContentPane().add(componenteBInt1);
        componenteBInt1.setBounds(310, 120, 212, 38);
        treeContainer2.getContentPane().add(componenteCInt1);
        componenteCInt1.setBounds(330, 190, 212, 38);

        simpleContainer1.setDividerLocation(300);
        simpleContainer1.getContentPane().add(componenteB2);
        simpleContainer1.getContentPane().add(componenteA2);

        treeContainer2.getContentPane().add(simpleContainer1);
        simpleContainer1.setBounds(300, 110, 200, 150);

        tabContainer1.setTabTitles("ComponentAInt, ComponentBInt, ComponentCInt");
        tabContainer1.getContentPane().add(componenteAInt2);
        tabContainer1.getContentPane().add(componenteBInt2);
        tabContainer1.getContentPane().add(componenteCInt2);

        treeContainer2.getContentPane().add(tabContainer1);
        tabContainer1.setBounds(330, 130, 200, 150);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Raíz");
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("ComponenteA");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("ComponenteB");
        treeNode1.add(treeNode2);
        treeContainer1.setEstructuraArbol(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treeContainer1.getContentPane().add(componenteA3);
        componenteA3.setBounds(140, 140, 114, 38);
        treeContainer1.getContentPane().add(componenteB3);
        componenteB3.setBounds(110, 170, 212, 38);

        treeContainer2.getContentPane().add(treeContainer1);
        treeContainer1.setBounds(230, 10, 400, 400);

        buttonPanelContainer1.getContentPane().add(treeContainer2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(buttonPanelContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(buttonPanelContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Punto de entrada principal para la aplicación de demostración.
     * <p>
     * Configura el Look and Feel de la interfaz a "Nimbus" y, a continuación,
     * crea y muestra el formulario {@code PruebaComponentesPaleta} en el
     * Event Dispatch Thread (EDT) de Swing para garantizar la seguridad de los hilos.
     *
     * @param args los argumentos de la línea de comandos (no se utilizan).
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaComponentesPaleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaComponentesPaleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaComponentesPaleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaComponentesPaleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruebaComponentesPaleta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private es.uned.TFGDavidGiner.components.containers.ButtonPanelContainer buttonPanelContainer1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteA componenteA1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteA componenteA2;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteA componenteA3;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteAInt componenteAInt1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteAInt componenteAInt2;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteB componenteB1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteB componenteB2;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteB componenteB3;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteBInt componenteBInt1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteBInt componenteBInt2;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteC componenteC1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteCInt componenteCInt1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteCInt componenteCInt2;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteD componenteD1;
    private es.uned.TFGDavidGiner.components.containers.SimpleContainer simpleContainer1;
    private es.uned.TFGDavidGiner.components.containers.TabContainer tabContainer1;
    private es.uned.TFGDavidGiner.components.containers.TreeContainer treeContainer1;
    private es.uned.TFGDavidGiner.components.containers.TreeContainer treeContainer2;
    // End of variables declaration//GEN-END:variables
}
