/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.uned.TFGDavidGiner.demo;

/**
 *
 * @author david
 */
public class TabContainersAnidados extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TabContainersAnidados.class.getName());

    /**
     * Creates new form TabsAnidados
     */
    public TabContainersAnidados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabContainer1 = new es.uned.TFGDavidGiner.components.containers.TabContainer();
        tabContainer2 = new es.uned.TFGDavidGiner.components.containers.TabContainer();
        tabContainer3 = new es.uned.TFGDavidGiner.components.containers.TabContainer();
        tabContainer4 = new es.uned.TFGDavidGiner.components.containers.TabContainer();
        tabContainer5 = new es.uned.TFGDavidGiner.components.containers.TabContainer();
        tabContainer6 = new es.uned.TFGDavidGiner.components.containers.TabContainer();
        componenteA1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteA();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabContainer6.getContentPane().add(componenteA1);

        tabContainer5.getContentPane().add(tabContainer6);

        tabContainer4.getContentPane().add(tabContainer5);

        tabContainer3.getContentPane().add(tabContainer4);

        tabContainer2.getContentPane().add(tabContainer3);

        tabContainer1.getContentPane().add(tabContainer2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TabContainersAnidados().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private es.uned.TFGDavidGiner.components.leafs.ComponenteA componenteA1;
    private es.uned.TFGDavidGiner.components.containers.TabContainer tabContainer1;
    private es.uned.TFGDavidGiner.components.containers.TabContainer tabContainer2;
    private es.uned.TFGDavidGiner.components.containers.TabContainer tabContainer3;
    private es.uned.TFGDavidGiner.components.containers.TabContainer tabContainer4;
    private es.uned.TFGDavidGiner.components.containers.TabContainer tabContainer5;
    private es.uned.TFGDavidGiner.components.containers.TabContainer tabContainer6;
    // End of variables declaration//GEN-END:variables
}
