/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.uned.TFGDavidGiner.demo;

/**
 * Ventana de demostración (JFrame) para visualizar un {@link es.uned.TFGDavidGiner.components.containers.TreeContainer}
 * con un único componente de hoja anidado.
 * <p>
 * Esta clase sirve como un entorno de prueba minimalista para verificar el
 * funcionamiento básico del {@code TreeContainer} y su capacidad para
 * mostrar un componente hijo, en este caso, un {@link es.uned.TFGDavidGiner.components.leafs.ComponenteA}.
 *
 * @author dginer
 * @version 1.0
 * @since 2025-07-13
 */
public class TreeContainersAnidados extends javax.swing.JFrame {

    /**
     * Constructor por defecto.
     * <p>
     * Crea una nueva instancia de la ventana de demostración e inicializa
     * todos sus componentes visuales.
     */
    public TreeContainersAnidados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        treeContainer3 = new es.uned.TFGDavidGiner.components.containers.TreeContainer();
        treeContainer1 = new es.uned.TFGDavidGiner.components.containers.TreeContainer();
        treeContainer2 = new es.uned.TFGDavidGiner.components.containers.TreeContainer();
        treeContainer4 = new es.uned.TFGDavidGiner.components.containers.TreeContainer();
        componenteA1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteA();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Raíz");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("C1");
        treeNode1.add(treeNode2);
        treeContainer3.setEstructuraArbol(new javax.swing.tree.DefaultTreeModel(treeNode1));

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Raíz");
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("C2");
        treeNode1.add(treeNode2);
        treeContainer1.setEstructuraArbol(new javax.swing.tree.DefaultTreeModel(treeNode1));

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Raíz");
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("C3");
        treeNode1.add(treeNode2);
        treeContainer2.setEstructuraArbol(new javax.swing.tree.DefaultTreeModel(treeNode1));

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Raíz");
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("C4");
        treeNode1.add(treeNode2);
        treeContainer4.setEstructuraArbol(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treeContainer4.getContentPane().add(componenteA1);
        componenteA1.setBounds(20, 210, 114, 38);

        treeContainer2.getContentPane().add(treeContainer4);
        treeContainer4.setBounds(0, 20, 400, 400);

        treeContainer1.getContentPane().add(treeContainer2);
        treeContainer2.setBounds(20, 30, 400, 400);

        treeContainer3.getContentPane().add(treeContainer1);
        treeContainer1.setBounds(30, 20, 400, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(treeContainer3, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(treeContainer3, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * El punto de entrada principal de la aplicación de demostración.
     *
     * @param args los argumentos de la línea de comandos (no se utilizan).
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TreeContainersAnidados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Crea y muestra el formulario en el Event Dispatch Thread de Swing */
        java.awt.EventQueue.invokeLater(() -> new TreeContainersAnidados().setVisible(true));
    }

    //<editor-fold defaultstate="collapsed" desc="Declaración de variables de componentes de la UI">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private es.uned.TFGDavidGiner.components.leafs.ComponenteA componenteA1;
    private es.uned.TFGDavidGiner.components.containers.TreeContainer treeContainer1;
    private es.uned.TFGDavidGiner.components.containers.TreeContainer treeContainer2;
    private es.uned.TFGDavidGiner.components.containers.TreeContainer treeContainer3;
    private es.uned.TFGDavidGiner.components.containers.TreeContainer treeContainer4;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
