/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.uned.TFGDavidGiner.demo;

/**
 * Ventana de demostración (JFrame) diseñada para probar la funcionalidad de
 * validación del framework de componentes.
 * <p>
 * Esta clase presenta una disposición compleja de componentes de hoja y contenedores,
 * donde cada grupo principal está encapsulado en un {@link es.uned.TFGDavidGiner.components.containers.ButtonPanelContainer}.
 * Esto permite probar cómo la lógica de validación (Aceptar/Cancelar) de la botonera
 * se propaga a través de diferentes niveles de anidación (Simple, Tab y Tree containers)
 * para validar todos los componentes hijos.
 *
 * @author david
 * @version 1.0
 * @since 13-07-2025
 */
public class ValidarFrame extends javax.swing.JFrame {

    /**
     * Constructor por defecto.
     * <p>
     * Crea una nueva instancia de la ventana de demostración e inicializa
     * todos sus componentes visuales.
     */
    public ValidarFrame() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botoneraContainer1 = new es.uned.TFGDavidGiner.components.containers.ButtonPanelContainer();
        simpleContainer1 = new es.uned.TFGDavidGiner.components.containers.SimpleContainer();
        componenteB1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteB();
        componenteA1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteA();
        botoneraContainer3 = new es.uned.TFGDavidGiner.components.containers.ButtonPanelContainer();
        tabContainer1 = new es.uned.TFGDavidGiner.components.containers.TabContainer();
        componenteA2 = new es.uned.TFGDavidGiner.components.leafs.ComponenteA();
        componenteB2 = new es.uned.TFGDavidGiner.components.leafs.ComponenteB();
        componenteC1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteC();
        botoneraContainer2 = new es.uned.TFGDavidGiner.components.containers.ButtonPanelContainer();
        treeContainer21 = new es.uned.TFGDavidGiner.components.containers.TreeContainer();
        componenteA3 = new es.uned.TFGDavidGiner.components.leafs.ComponenteA();
        componenteB3 = new es.uned.TFGDavidGiner.components.leafs.ComponenteB();
        componenteC2 = new es.uned.TFGDavidGiner.components.leafs.ComponenteC();
        simpleContainer2 = new es.uned.TFGDavidGiner.components.containers.SimpleContainer();
        componenteB4 = new es.uned.TFGDavidGiner.components.leafs.ComponenteB();
        componenteA4 = new es.uned.TFGDavidGiner.components.leafs.ComponenteA();
        tabContainer2 = new es.uned.TFGDavidGiner.components.containers.TabContainer();
        componenteA5 = new es.uned.TFGDavidGiner.components.leafs.ComponenteA();
        componenteB5 = new es.uned.TFGDavidGiner.components.leafs.ComponenteB();
        componenteC3 = new es.uned.TFGDavidGiner.components.leafs.ComponenteC();
        componenteD1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteD();
        treeContainer22 = new es.uned.TFGDavidGiner.components.containers.TreeContainer();
        componenteAInt2 = new es.uned.TFGDavidGiner.components.leafs.ComponenteAInt();
        componenteBInt1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteBInt();
        componenteD2 = new es.uned.TFGDavidGiner.components.leafs.ComponenteD();
        componenteAInt1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteAInt();
        componenteBInt2 = new es.uned.TFGDavidGiner.components.leafs.ComponenteBInt();
        componenteCInt1 = new es.uned.TFGDavidGiner.components.leafs.ComponenteCInt();
        jButton1 = new javax.swing.JButton();
        botoneraContainer4 = new es.uned.TFGDavidGiner.components.containers.ButtonPanelContainer();
        componenteA6 = new es.uned.TFGDavidGiner.components.leafs.ComponenteA();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        simpleContainer1.getContentPane().add(componenteB1);
        simpleContainer1.getContentPane().add(componenteA1);

        botoneraContainer1.getContentPane().add(simpleContainer1);

        tabContainer1.setTabTitles("Pestaña 1,Pestaña b,Pestaña 3");
        tabContainer1.getContentPane().add(componenteA2);
        tabContainer1.getContentPane().add(componenteB2);
        tabContainer1.getContentPane().add(componenteC1);

        botoneraContainer3.getContentPane().add(tabContainer1);

        treeContainer21.setDesignTimeSelectionPath("Raíz, ComponenteC");
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Raíz");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("ComponenteA");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("ComponenteB");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("ComponenteC");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("SimpleContainer");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("TabContainer");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("TreeContainer");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("ComponenteD");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("ComponenteAInt");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("ComponenteBInt");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("ComponenteCInt");
        treeNode1.add(treeNode2);
        treeContainer21.setEstructuraArbol(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treeContainer21.getContentPane().add(componenteA3);
        componenteA3.setBounds(10, 70, 114, 38);
        treeContainer21.getContentPane().add(componenteB3);
        componenteB3.setBounds(0, 110, 212, 38);
        treeContainer21.getContentPane().add(componenteC2);
        componenteC2.setBounds(-20, 90, 189, 43);

        simpleContainer2.getContentPane().add(componenteB4);
        simpleContainer2.getContentPane().add(componenteA4);

        treeContainer21.getContentPane().add(simpleContainer2);
        simpleContainer2.setBounds(50, 50, 200, 150);

        tabContainer2.setTabTitles("ComponenteA, ComponenteB, ComponenteC, ComponenteD");
        tabContainer2.getContentPane().add(componenteA5);
        tabContainer2.getContentPane().add(componenteB5);
        tabContainer2.getContentPane().add(componenteC3);
        tabContainer2.getContentPane().add(componenteD1);

        treeContainer21.getContentPane().add(tabContainer2);
        tabContainer2.setBounds(1, 1, 420, 150);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("JTree");
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("ComponenteAInt");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("ComponenteBInt");
        treeNode1.add(treeNode2);
        treeContainer22.setEstructuraArbol(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treeContainer22.getContentPane().add(componenteAInt2);
        componenteAInt2.setBounds(30, 30, 106, 38);
        treeContainer22.getContentPane().add(componenteBInt1);
        componenteBInt1.setBounds(20, 100, 212, 38);

        treeContainer21.getContentPane().add(treeContainer22);
        treeContainer22.setBounds(1, 1, 438, 320);
        treeContainer21.getContentPane().add(componenteD2);
        componenteD2.setBounds(70, 130, 114, 38);
        treeContainer21.getContentPane().add(componenteAInt1);
        componenteAInt1.setBounds(130, 100, 106, 38);
        treeContainer21.getContentPane().add(componenteBInt2);
        componenteBInt2.setBounds(100, 90, 212, 38);
        treeContainer21.getContentPane().add(componenteCInt1);
        componenteCInt1.setBounds(50, 120, 212, 38);

        botoneraContainer2.getContentPane().add(treeContainer21);

        jButton1.setText("ComponenteB3 ERROR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        botoneraContainer4.getContentPane().add(componenteA6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botoneraContainer2, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton1)
                        .addGap(11, 11, 11)
                        .addComponent(botoneraContainer4, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botoneraContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botoneraContainer3, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botoneraContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(botoneraContainer3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(botoneraContainer2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(40, 40, 40))
                            .addComponent(botoneraContainer4, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        /**
     * Manejador de eventos para el clic en {@code jButton1}.
     * <p>
     * Modifica la propiedad {@code propertyName} de {@code componenteB3} a "ERROR".
     * Esto está diseñado para probar la lógica de validación especial del
     * {@link ComponenteB}, que lo marcará como inválido si su nombre de propiedad es "ERROR".
     *
     * @param evt El evento de acción.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.componenteB3.setPropertyName("ERROR");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * El punto de entrada principal de la aplicación.
     *
     * @param args los argumentos de la línea de comandos (no se utilizan).
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValidarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Crea y muestra el formulario en el Event Dispatch Thread de Swing */
        java.awt.EventQueue.invokeLater(() -> new ValidarFrame().setVisible(true));
    }

    //<editor-fold defaultstate="collapsed" desc="Declaración de variables de componentes de la UI">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private es.uned.TFGDavidGiner.components.containers.ButtonPanelContainer botoneraContainer1;
    private es.uned.TFGDavidGiner.components.containers.ButtonPanelContainer botoneraContainer2;
    private es.uned.TFGDavidGiner.components.containers.ButtonPanelContainer botoneraContainer3;
    private es.uned.TFGDavidGiner.components.containers.ButtonPanelContainer botoneraContainer4;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteA componenteA1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteA componenteA2;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteA componenteA3;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteA componenteA4;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteA componenteA5;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteA componenteA6;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteAInt componenteAInt1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteAInt componenteAInt2;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteB componenteB1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteB componenteB2;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteB componenteB3;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteB componenteB4;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteB componenteB5;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteBInt componenteBInt1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteBInt componenteBInt2;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteC componenteC1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteC componenteC2;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteC componenteC3;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteCInt componenteCInt1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteD componenteD1;
    private es.uned.TFGDavidGiner.components.leafs.ComponenteD componenteD2;
    private javax.swing.JButton jButton1;
    private es.uned.TFGDavidGiner.components.containers.SimpleContainer simpleContainer1;
    private es.uned.TFGDavidGiner.components.containers.SimpleContainer simpleContainer2;
    private es.uned.TFGDavidGiner.components.containers.TabContainer tabContainer1;
    private es.uned.TFGDavidGiner.components.containers.TabContainer tabContainer2;
    private es.uned.TFGDavidGiner.components.containers.TreeContainer treeContainer21;
    private es.uned.TFGDavidGiner.components.containers.TreeContainer treeContainer22;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
